before_script:
  - apt-get update -y
  - apt-get install default-jre -y
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod a+x lein
  - export LEIN_ROOT=1
  - PATH=$PATH:.
  - lein deps

build:
  stage: build
  script: lein sub uberjar
  only:
    - stable

test:
  state: test
  script: lein sub test
